[project]
name = "kiln_string"
version = "0.0.3"
language = "c"
build_type = ["ingot"]
src_dirs = ["src"]
include_dirs = ["include"]


[build_options]
compiler_path = "gcc"
debug_flags = ["-g", "-O0", "-fsanitize=undefined"]
release_flags = ["-O3"]
shared_flags = ["-Wall"]